--- 
- hosts: jenkins_servers
  gather_facts: no  
  become: yes
  vars:
    - jenkins_download_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    - jenkins_repo_destination: /etc/yum.repos.d/jenkins.repo
    - jenkins_key_url: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
  tasks:
    - name: Install java jdk to run jenkins and wget to download jenkins binary
      package:
        name: 
          - java-17-openjdk
          - wget
        state: present

    - name: Download jenkins repository file
      get_url:
        url: "{{ jenkins_download_url }}"
        dest: "{{ jenkins_repo_destination }}"
        mode: '0644'

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ jenkins_key_url }}"
      become: yes

    - name: Install jenkins
      yum:
        name: jenkins
        state: present
      notify : 
        - jenkins-installed  

  handlers:
    - name: Reload and restart systemd services
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl enable jenkins
        systemctl start jenkins  
      listen: "jenkins-installed"

