---
- hosts: localhost
  vars_files:
    - /home/ansible/keys/aws-access.yml
  become: yes
  tasks:
    - name: gather insances info
      ec2_instance_info:
        access_key: "{{ ACCESS_ID }}"
        secret_key: "{{ SECRET_ID }}" 
        region: "{{ REGION }}"
        filters:
          "tag:function": webserver
          instance-state-name: ["running"]
      register: web_app_instances

    - name: extract public IP addresses of the instances
      set_fact:
        public_ips: "{{ web_app_instances.instances | map(attribute='public_ip_address') | list }}"

    - name: view public IP addresses
      debug:
        var: public_ips

    - name: create a dynamic host to inventory
      add_host:
        hostname: "ec2-user@{{ item }}"
        groupname: react_hosts
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: "{{ public_ips }}"

- hosts: react_hosts
  become: yes
  gather_facts: no
  vars_files:
    - /home/ansible/keys/aws-access.yml
  tasks:
  - name: install docker
    dnf:
      name: docker
      state: present    

  - name: start and enable docker
    systemd:
      name: docker
      state: started
      enabled: yes    

  - name: Ensure Docker group exists
    group:
      name: docker
      state: present

  - name: Add ec2-user to Docker group
    user:
      name: ec2-user
      groups: docker
      append: yes   

  - name: Perform ECR login
    shell: "aws ecr get-login-password --region {{ REGION }} | docker login --username AWS --password-stdin {{ ECR_REPO_URL }}"
    args:
      executable: /bin/bash
    become: yes
    become_user: ec2-user
    register: ecr_login_result

  - name: Display ECR login result
    debug:
      var: ecr_login_result.stdout_lines     